name: Bot Run Job
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '0/15 * * * *'


jobs:
  run_bb_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      # - uses: szenius/set-timezone@v1.0
      #   with:
      #     timezoneLinux: "Asia/Tokyo"
      - name: Fetch DB from gist
        run: curl -sL ${{ secrets.GIST_URL }}/raw/db.json -o db.json
      - run: node app
        env:
          TIMETREE_TOKEN: ${{ secrets.TIMETREE_TOKEN }}
          TIMETREE_CALENDAR_ID: ${{ secrets.TIMETREE_CALENDAR_ID }}
          ICS_URL: ${{ secrets.ICS_URL }}
          BOT_NAME: ${{ secrets.BOT_NAME }}
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: ${{ secrets.GIST_URL }}
          gist_title: db.json
          gist_description: A database of ics-to-timetree
          github_file: db.json